# Generated by Django 5.2.3 on 2025-06-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Produto do Estoque',
                'verbose_name_plural': 'Produtos do Estoque',
                'db_table': 'tb_produto',
                'ordering': ['nome'],
                'get_latest_by': 'data_validade',
            },
        ),
    ]
