# Generated by Django 5.2.3 on 2025-09-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('LIMPEZA', 'Limpeza'), ('ESCOLAR', 'Escolar'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
    ]
