# Generated by Django 5.2.3 on 2025-09-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_quantidade_alter_produto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lote de Produto',
                'verbose_name_plural': 'Lotes de Produtos',
                'db_table': 'tb_lote',
                'ordering': ['data_validade'],
                'get_latest_by': 'data_validade',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('LIMPEZA', 'Limpeza'), ('ESCOLAR', 'Escolar'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produtos',
                'db_table': 'tb_tipo_produto',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tipoproduto'),
        ),
    ]
