# Generated by Django 5.2.3 on 2025-10-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='origem_compra',
            field=models.CharField(choices=[('COMUM', 'Compra Comum'), ('AGRICULTURA', 'Agricultura Familiar')], default='COMUM', max_length=15, verbose_name='Origem da Compra'),
        ),
    ]
