# Generated by Django 5.2.3 on 2025-10-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_tipoproduto_origem_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='unidade_medida',
            field=models.CharField(choices=[('KG', 'Quilogramas (KG)'), ('G', 'Gramas (g)'), ('L', 'Litros (L)'), ('ML', 'Mililitros (mL)'), ('UN', 'Unidades (Un)'), ('CX', 'Caixas (Cx)')], default='UN', max_length=5, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_fabricacao',
            field=models.DateField(verbose_name='Data de Fabricação'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_validade',
            field=models.DateField(verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
