# Generated by Django 5.2.3 on 2025-10-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_tipoproduto_unidade_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='lote',
            name='quantidade_pacotes',
            field=models.IntegerField(default=0, help_text='Quantidade física de pacotes ou unidades.', verbose_name='Nº de Pacotes/Itens'),
        ),
        migrations.AddField(
            model_name='lote',
            name='quantidade_por_pacote',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Peso ou volume de cada pacote/item.', max_digits=10, verbose_name='Peso/Volume por Pacote'),
            preserve_default=False,
        ),
    ]
