# Generated by Django 5.2.3 on 2025-10-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_remove_lote_quantidade_lote_quantidade_pacotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quantidade_por_pacote',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Peso ou volume de cada pacote/item.', max_digits=10, verbose_name='Peso/Volume por Pacote'),
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='unidade_medida',
            field=models.CharField(choices=[('KG', 'Quilogramas (KG)'), ('G', 'Gramas (g)'), ('L', 'Litros (L)'), ('ML', 'Mililitros (mL)'), ('UN', 'Unidades (Un)'), ('CX', 'Caixas (Cx)'), ('NA', 'Não Aplicável (N/A)')], default='NA', max_length=5, verbose_name='Unidade de Medida'),
        ),
    ]
