# Generated by Django 5.2.3 on 2025-10-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_lote_quantidade_por_pacote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quantidade_por_pacote',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Peso ou volume de cada pacote/item.', max_digits=10, null=True, verbose_name='Peso/Volume por Pacote'),
        ),
    ]
