# Generated by Django 5.2.3 on 2025-10-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_lote_quantidade_por_pacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='possui_data_fabricacao',
            field=models.BooleanField(default=True, verbose_name='Possui Data de Fabricação?'),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='possui_data_validade',
            field=models.BooleanField(default=True, verbose_name='Possui Data de Validade?'),
        ),
    ]
