# Generated by Django 5.2.3 on 2025-10-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_tipoproduto_possui_data_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fabricação'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
    ]
