# Generated by Django 5.2.3 on 2025-10-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_lote_data_fabricacao_alter_lote_data_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='produtos.tipoproduto'),
        ),
    ]
