# Generated by Django 5.2.3 on 2025-12-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_lote_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário (R$)'),
        ),
    ]
