# Generated by Django 5.2.3 on 2025-12-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_lote_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Produtos inativos não aparecem para novos pedidos, mas mantêm histórico', verbose_name='Ativo'),
        ),
    ]
