# Generated by Django 5.2.3 on 2025-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_tipoproduto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='justificativa_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
