# Generated by Django 4.2.27 on 2026-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_pedido_justificativa_rejeicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao_carne',
            field=models.TextField(blank=True, null=True, verbose_name='Solicitação de Carne/Perecíveis'),
        ),
    ]
