# Generated by Django 4.2.27 on 2026-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_pedido_observacao_carne'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carne_comprada',
            field=models.BooleanField(default=False, verbose_name='Compra de Carne Realizada'),
        ),
    ]
