# Generated by Django 5.2.3 on 2026-01-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_pedido_carne_comprada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='justificativa_secretario',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
