# Generated by Django 5.2.3 on 2026-01-16 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_pedido_justificativa_secretario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
    ]
