# Generated by Django 5.2.3 on 2026-01-16 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_lote_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada'),
        ),
    ]
