# Generated by Django 5.2.3 on 2026-01-15 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Um usuário com este nome já existe.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e espaços apenas.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+- ]+$', 'Informe um nome de usuário válido. Este valor pode conter apenas letras, números, espaços e os caracteres @/./+/-/_.')]),
        ),
    ]
