# Generated by Django 5.2.3 on 2026-01-19 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_cargo_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escola', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
