# Generated by Django 5.2.3 on 2026-01-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilescola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('SECRETARIO', 'Secretário'), ('DIRETOR', 'Diretor Escolar'), ('NUTRICIONISTA', 'Nutricionista')], max_length=20),
        ),
    ]
